### ISSUE TITLE
Форма для создания новости или статьи

### ISSUE THREAD

**Issue by illiiiillllilii** [codex-team/codex.edu#22]
### TODO
- [x] Необходимо вынести форму для создания новости или статьи отдельную от админки страницу
- [x] в header вынести текущий путь до страницы
- [x] возможность редактирования и удаления страниц
- [x] проверки на валидность операций (так как можно попытаться подменить type и parent в $_GET)

**Comment by illiiiillllilii** [comment]
А нужен ли нам select?
- новости создаются с главной страницы
- личные страницы с профиля
- подстраницы можно создавать из страниц

**Comment by neSpecc** [comment]
какой select?

**Comment by illiiiillllilii** [comment]
тот, который позволяет выбрать одну страницу из списка.
учитель не будет искать нужную страницу-родителя среди всех страниц. по крайней мере так не должно быть.

**Comment by illiiiillllilii** [comment]
ясно же, что будет лучше, если для создания новой страницы нужен заголовок и текст.
все остальные привязки система сделает автоматически.

суть в том, что форма будет одна, но вызываться она будет из разных частей сайта и от этого зависит, куда эта страница приклеется

**Comment by illiiiillllilii** [comment]
Ветка: https://github.com/codex-team/codex.edu/tree/form_for_pages

Сделал возможность создания страниц и новостей. Кнопки есть на главной странице, в профиле и в списке ссылок под каждой страницей.

**Comment by loopdigga98** [comment]
Мб добавим codex.editor?

**Comment by illiiiillllilii** [comment]
Что бы добавить, он должен быть готов

Это не задача первой необходимости

**Comment by loopdigga98** [comment]
Это было просто предложение, я знаю, что он не готов

**Comment by illiiiillllilii** [comment]
так-то, конечно, добавим
