### ISSUE TITLE
Деплой на school332.ru

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.edu#293]
- [ ] #172 заполнить сайт информацией
- [ ] создать приложения в соцсетях для входа
    - [x] vk
    - [ ] facebook
    - [x] twitter
- [ ] создать аккаунт в sendgrip
- [x] увеличить максимальный размер загружаемых файлов
- [x] codex-team/codex.special#18 настроить codex.special
- [ ] #183 создать страницу контактов 
- [x] #263 подключить emoji-parser
---
- [ ] подключить метрику
- [ ] #267 установить виджет госсайтов

**Comment by talyguryn** [comment]
разбил на мелкие подзадачи
