### ISSUE TITLE
Свежие проблемы, которые ждут скорейшего решения

### ISSUE THREAD

**Issue by illiiiillllilii** [codex-team/codex.edu#91]
- [ ] доделать форму публикации новости на главной странице (добавить флажки) @neSpecc 
- [ ] клиент-рефакторинг 
- [ ] наполнить сайт контентом @PolinaShneider #69
- [ ] ссылка на список учителей/пользователей #99 
- [ ] починить загрузку файлов @neSpecc #85
- [ ] дизайн страницы статьи (автор, дата, файлы)
